apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-box-api-user
  labels:
    app: dprofile-box-api-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-box-api-user
  template:
    metadata:
      labels:
        app: profile-box-api-user
    spec:
      containers:
      - name: profile-box-api-user
        image: 204770130849.dkr.ecr.ap-northeast-2.amazonaws.com/profile-box-api-user:406cd9206107c3b2366e456515d6d636564f3017
      imagePullSecrets:
      - name: ecr-secret
