apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-box-api-user
  labels:
    app: dprofile-box-api-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-box-api-user
  template:
    metadata:
      labels:
        app: profile-box-api-user
    spec:
      containers:
      - name: profile-box-api-user
        image: 204770130849.dkr.ecr.ap-northeast-2.amazonaws.com/profile-box-api-user:f6dc51f9ad65c2de1efe58c24ced8e9bf7d78dc9
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      imagePullSecrets:
      - name: ecr-secret
