apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-front
  labels:
    app: demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: demo-frontend
        image: 204770130849.dkr.ecr.ap-northeast-2.amazonaws.com/profile-box-front:6dfd5c58e7cadf289eab49f059951974bc4f806d
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
