apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-user
  labels:
    app: dev-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-user
  template:
    metadata:
      labels:
        app: dev-user
    spec:
      containers:
      - name: dev-user
        image: 204770130849.dkr.ecr.ap-northeast-2.amazonaws.com/profile-box-api-user:195341ffe4f7c4240a1c80dc0a471cf452c1dc8d
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dev-user
spec:
  selector:
    app: dev-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
